aliYun:
  ak : "ak"
  sk : "sk"
  sign : "sign"
  template_bind : "SMS_10086"
  template_resetPassword : "SMS_10010"

#
# NanoLimbo 配置
#

# 服务器的地址和端口. 设置ip为空使用本机ip地址
bind:
  ip: 'localhost'
  port: 65535

# 最多可加入的玩家数量
# 设置为 -1 不限制玩家数量
maxPlayers: 100

# 服务器列表中显示的信息
ping:
  description: '{"text": "&9NanoLimbo"}'
  version: 'NanoLimbo'

# 可用的世界类型: OVERWORLD, NETHER, THE_END
dimension: THE_END

# 是否在玩家列表中显示玩家
# 在1.16.5中无法关闭此功能，为了防止客户端无法正常工作。
playerList:
  enable: false
  username: 'NanoLimbo'

# 是否在玩家列表中显示页眉和页脚
headerAndFooter:
  enable: false
  header: '{"text": "&eWelcome!"}'
  footer: '{"text": "&9NanoLimbo"}'

# 出生点设置
spawnPosition:
  'x': 0.0
  'y': 400.0
  'z': 0.0
  'yaw': 0.0
  'pitch': 0.0

# 玩家的游戏模式
# 0 - 生存
# 1 - 创造
# 2 - 冒险
# 3 - 旁观者
gameMode: 0

# F3中显示的服务器名称
brandName:
  enable: true
  content: 'NanoLimbo'

# 玩家加入服务器时发送的消息
joinMessage:
  enable: true
  text: '{"text": "&eWelcome to the Limbo!"}'

# 玩家加入时显示boos血条
# 只能在1.9版本以上工作
bossBar:
  enable: true
  text: '{"text": "Welcome to the Limbo!"}'
  health: 1.0
  # A血条颜色: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
  color: PINK
  # 血条分割线: SOLID, DASHES_6, DASHES_10, DASHES_12, DASHES_20
  division: SOLID

# 显示标题和副标题
title:
  enable: false
  # 如果只显示主标题请将 subtitle 设置为空
  title: '{"text": "&9&lWelcome!"}'
  # 如果只显示副标题，请将 title 设置为空
  subtitle: '{"text": "&6NanoLimbo"}'
  # 淡入时间 (1秒 = 20 ticks)
  fadeIn: 10
  # 显示时间
  stay: 100
  # 淡出时间
  fadeOut: 10

# 玩家信息转发支持
# 可用类型:
#  - NONE
#  - LEGACY
#  - MODERN
#  - BUNGEE_GUARD
# 如果你使用 MODERN ,请不要加密
infoForwarding:
  type: NONE
  secret: '<YOUR_SECRET_HERE>'
  tokens:
    - '<BUNGEE_GUARD_TOKEN>'

# 连接超时时间 (毫秒)
readTimeout: 30000

# 日志级别. 如果在生产环境, 我建议使用2级
# 日志级别:
# 0 - 只显示 errors
# 1 - 显示 errors, warnings
# 2 - 显示 errors, warnings, info
# 3 - 显示 errors, warnings, info, debug
debugLevel: 2

# 如果你不知道这是什么，请不要修改
netty:
  # Use Linux native transport type, if it possible
  useEpoll: true
  # EventLoopGroup threads count
  threads:
    bossGroup: 1
    workerGroup: 4